config/routes.rb
Rails.application.routes.draw do
  resources :importations
  resources :superviseurs
  resources :tiers_types
  resources :users
  resource :user_sessions, only: [:create, :new, :destroy]
  resources :travaux_artisans
  get 'config' => 'config#index'
  resources :travaux
  resources :biens
  resources :tiers
  root 'home#index'
  get 'home/index'

  get 'statistiques' => 'statistiques#index'

	resources :travaux_statuts
	resources :travaux_types
  resources :travaux_lignes
	resources :bien_types

  resources :societes, only: [:edit, :update]

	post 'newligne' => 'travaux#newligne'

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'factures' => 'factures#index'
  post 'factures' => 'factures#paye'
  post 'factures_envoye' => 'factures#envoye'

end

app/models/travaux_type.rb
class TravauxType < ActiveRecord::Base
	has_many :travaux
end

app/controllers/travaux_controller.rb
class TravauxController < ApplicationController
	include ApplicationHelper
  before_action :set_travail, only: [:show, :edit, :update, :destroy]

  # GET /travaux
  # GET /travaux.json
  def index
  	tiers_id = params["tiers"]
  	bien_id = params["bien"]
  	@titre = "TRAVAUX"
  	if params["artisan"]
			@travauxartisans = TravauxArtisan.includes(:travail, :tier).where(tier_id: params["artisan"])
			artisan = Tier.find(params["artisan"])
			@titre += " - #{artisan.nom_complet}"
			gon.travaux = []
	  	@travauxartisans.each do |ta|
	  		artisans = TravauxArtisan.where(travail_id: ta.travail_id)
	  		artisans_tab = []
	  		artisans.each do |artisan|
	  			artisans_tab << artisan.tier.nom_complet unless artisans_tab.include?(artisan.tier.nom_complet)
	  		end
				proprietaires = []
	      proprietaires << ta.travail.bien.proprietaire.nom_complet if ta.travail.bien.proprietaire
	      proprietaires << ta.travail.bien.coproprietaire.nom_complet if ta.travail.bien.coproprietaire
	      locataires = []
	      locataires << ta.travail.bien.locataire.nom_complet if ta.travail.bien.locataire
	      locataires << ta.travail.bien.colocataire.nom_complet if ta.travail.bien.colocataire
	  		gon.travaux << {id: ta.travail_id,
	  										type: ta.travail.travaux_type.nom,
												statut: ta.travail.travaux_statut.nom,
												date: ta.travail.created_at.strftime("%d/%m/%Y"),
												bien: ta.travail.bien.nom,
												proprietaire: proprietaires.join(", "),
												locataire: locataires.join(", "),
												prestataires: artisans_tab.join(", ")
											 }
			end
  	else
			@travaux = Travail.all
			if tiers_id
		  	@travaux = @travaux.joins(:bien).where("biens.proprietaire_id=? OR biens.locataire_id=?", tiers_id, tiers_id)
		  	tier = Tier.find(tiers_id)
				@titre += " - #{tier.nom_complet}"
		  end
		  if bien_id
		  	@travaux = @travaux.where(:bien_id => bien_id)
		  	bien = Bien.find(bien_id)
				@titre += " - #{bien.nom}"
		  end

	  	gon.travaux = []
	  	@travaux.each do |travail|
	  		artisans = TravauxArtisan.includes(:tier).where(travail_id: travail.id)
	  		artisans_tab = []
	  		artisans.each do |artisan|
	  			artisans_tab << artisan.tier.nom_complet unless artisans_tab.include?(artisan.tier.nom_complet)
	  		end
				proprietaires = []
	      proprietaires << travail.bien.proprietaire.nom_complet if travail.bien.proprietaire
	      proprietaires << travail.bien.coproprietaire.nom_complet if travail.bien.coproprietaire
	      locataires = []
	      locataires << travail.bien.locataire.nom_complet if travail.bien.locataire
	      locataires << travail.bien.colocataire.nom_complet if travail.bien.colocataire
	  		gon.travaux << {id: travail.id,
	  										type: travail.travaux_type.nom,
												statut: travail.cancel ? "Annulé" : travail.travaux_statut.nom,
												date: travail.created_at.strftime("%d/%m/%Y"),
												bien: travail.bien.nom,
												proprietaire: proprietaires.join(", "),
												locataire: locataires.join(", "),
												prestataires: artisans_tab.join(", ")
											 }
		  end
		end
    @new_path = new_travail_path
    @new_path += "?bien=#{bien_id}" if bien_id
		@new_path += "?tiers=#{tiers_id}" if tiers_id
  end

  # GET /travaux/1
  # GET /travaux/1.json
  def show
  	@lignes = TravauxLigne.where(travail_id: @travail.id)
  	@artisans = Tier.where(tiers_type_id: 3).order(:raison_sociale, :nom, :prenom)
  	@prestataires = TravauxArtisan.where(travail_id: @travail.id).order(:id)
  	@superviseurs = Superviseur.where(travail_id: @travail.id)
  	@email = "Bonjour\n\nNous avons besoin de faire appel à vos services:\nNature des travaux : #{@travail.travaux_type.nom}"
  	@email += "\n\nLogement concerné :\n\nBien : #{@travail.bien.nom}\nAdresse : #{@travail.bien.adresse_complete}\nPropriétaire : #{@travail.bien.proprietaire.nom_complet}"
  	@email += "\nLocataire : #{@travail.bien.locataire.nom_complet}" if @travail.bien.locataire
  	@email += "\n\nVous remerciant de votre retour.\nCordialement,"
  	@email += "\n\n#{current_user.signature}" if current_user.signature
		@email_bailleur = "Bonjour\n\nJe vous transmets en pièce jointe pour avis le devis pour les travaux à réaliser à l'adresse suivante :"
  	@email_bailleur += "\n\nBien : #{@travail.bien.nom}\nAdresse : #{@travail.bien.adresse_complete}"
  	@email_bailleur += "\n\nAu plaisir de recevoir votre retour.\nVous remerciant de votre confiance.\n\nCordialement,"
  	@email_bailleur += "\n\n#{current_user.signature}" if current_user.signature
		@email_accord = "Bonjour\n\nJe vous transmets le bon pour accord d'intervention pour le logement situé:"
		@email_accord += "\n\nBien : #{@travail.bien.nom}\nAdresse : #{@travail.bien.adresse_complete}"
  	@email_accord += "\n\nCordialement,"
  	@email_accord += "\n\n#{current_user.signature}" if current_user.signature
  	Messagerie.joins(:travaux_ligne).where("travaux_lignes.travail_id": @travail.id, user_id: current_user.id).destroy_all
		@travaux_ligne = TravauxLigne.new
		@travaux_ligne.travail_id = @travail.id
		@supprimable = TravauxArtisan.where(travail_id: @travail.id, demande: true).count == 0
  end

  # GET /travaux/new
  def new
    @travail = Travail.new
    @travail.bien_id = params["bien"] if params["bien"]
		tiers_id = params["tiers"]
		@biens = tiers_id ? Bien.where("proprietaire_id=? OR locataire_id=?", tiers_id, tiers_id) : Bien.all
  end

  # GET /travaux/1/edit
  def edit
  end

  # POST /travaux
  # POST /travaux.json
  def create
    @travail = Travail.new(travail_params)
    @travail.user_id = current_user.id
    @travail.travaux_statut_id = 1
    respond_to do |format|
      if @travail.save
				# Ajouter les superviseurs généraux
				User.all.each do |user|
					Superviseur.create :travail_id => @travail.id, :user_id => user.id if user.superviseur
        end
				format.html { redirect_to @travail, notice: 'Travail was successfully created.' }
        format.json { render :show, status: :created, location: @travail }
      else
        format.html { render :new }
        format.json { render json: @travail.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /newligne
  def newligne
  	@ligne = TravauxLigne.new(travaux_ligne_params, user_id: current_user.id)
  	respond_to do |format|
      if @ligne.save
        format.html { redirect_to "/travaux/#{params['idtravail']}#nouvelleligne", notice: 'Ligne was successfully created.' }
      end
    end
  end

  # PATCH/PUT /travaux/1
  # PATCH/PUT /travaux/1.json
  def update
    if travail_params["cancel"]=="1"
			TravauxLigne.create(travail_id: @travail.id,
													detail: "Annulation du travail :\n#{travail_params["cancel_raison"]}",
													message_automatique: true,
													user_id: current_user.id)
		end
		respond_to do |format|
      if @travail.update(travail_params)
        format.html { redirect_to @travail, notice: 'Travail was successfully updated.' }
        format.json { render :show, status: :ok, location: @travail }
      else
        format.html { render :edit }
        format.json { render json: @travail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travaux/1
  # DELETE /travaux/1.json
  def destroy
    @travail.destroy
    respond_to do |format|
      format.html { redirect_to travaux_url, notice: 'Travail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travail
      @travail = Travail.includes(:travaux_type, :travaux_statut, :bien).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travail_params
      params.require(:travail).permit(:bien_id, :travaux_statut_id, :travaux_type_id, :cancel, :cancel_raison)
    end

		# Never trust parameters from the scary internet, only allow the white list through.
    def travaux_ligne_params
      params.require(:travaux_ligne).permit(:travail_id, :detail, :piece_jointe)
    end
end

app/helpers/travaux_helper.rb
module TravauxHelper
end

app/views/travaux/_en_tete.erb
<div class="col-md-12 cadre_bleu">
	<div class="col-md-6">
		<dl class="dl-horizontal">
			<dt><strong>Bien :</strong></dt>
			<dd><%= link_to @travail.bien.nom_ref, bien_path(@travail.bien_id) %></dd>
			<dt><strong>Type de travail:</strong></dt>
			<dd><%= @travail.travaux_type.nom %></dd>
			<dt><strong>Date de création:</strong></dt>
			<dd><%= @travail.created_at.in_time_zone(current_user.timezone).strftime("%d/%m/%Y %H:%M") %></dd>
			<dt><strong>Créateur:</strong></dt>
			<dd><%= image_tag @travail.user.avatar.url(:thumb), class: "image_ronde_petite", title: "Créé par #{@travail.user.name}" %></dd>
		</dl>
	</div>
	<div class="col-md-6">
		<dl class="dl-horizontal">
			<dt><strong>Propriétaires:</strong></dt>
			<dd>
				<%= (@travail.bien.proprietaire_id ? link_to(@travail.bien.proprietaire.nom_complet, tier_path(@travail.bien.proprietaire_id)) : '') %>
				<%= (@travail.bien.coproprietaire_id ? link_to(@travail.bien.coproprietaire.nom_complet, tier_path(@travail.bien.coproprietaire_id)) : '') %>
			</dd>
			<dt><strong>Locataires:</strong></dt>
			<dd>
				<%= (@travail.bien.locataire_id ? link_to(@travail.bien.locataire.nom_complet, tier_path(@travail.bien.locataire_id)) : '') %>
				<%= (@travail.bien.colocataire_id ? link_to(@travail.bien.colocataire.nom_complet, tier_path(@travail.bien.colocataire_id)) : '') %>
			</dd>
			<dt><strong>Syndic:</strong></dt>
			<dd><%= (@travail.bien.syndic_id ? link_to(@travail.bien.syndic.nom_complet, tier_path(@travail.bien.syndic_id)) : '') %></dd>
			<dt><strong>Superviseurs:</strong></dt>
			<dd>
				<% @superviseurs.each do |superviseur| %>
					<% if superviseur.user_id==current_user.id %>
            <%= link_to image_tag(superviseur.user.avatar.url(:thumb), class: "image_ronde_petite", title: superviseur.user.name), superviseur, method: :delete, data: { confirm: 'Voulez-vous vous retirer de la liste des superviseurs pour ce travail ?' } %>
          <% else %>
              <%= image_tag(superviseur.user.avatar.url(:thumb), class: "image_ronde_petite", title: superviseur.user.name) %>
          <% end %>
				<% end %>
				<% @superviseur = Superviseur.new %>
				<% @superviseur.travail_id = @travail.id %>
				<% @superviseur.user_id = current_user.id %>
				<div hidden="true">
					<%= render :partial => 'superviseurs/form' %>
				</div>
				<% unless @travail.cancel %>
					<i class="fa fa-plus" onclick="$('#superviseurSubmitButton').trigger('click');" title="S'ajouter à la liste des superviseurs: permet de recevoir des notifications lors de changements sur ce travail"></i>
				<% end %>
			</dd>
		</dl>
		<% unless @travail.cancel %>
			<% if @supprimable %>
					<p align="right"><%= link_to 'Supprimer', @travail, method: :delete, data: { confirm: 'Etes-vous sûr de vouloir supprimer définitivement ce travail ?' }, :class => 'btn btn-danger' %></p>
			<% elsif @travail.travaux_statut.ordre<6.0 %>
					<p align="right"><button class='btn btn-danger' data-toggle="modal" data-target="#cancelModal">Annuler le travail</button></p>
					<div hidden><%= render :partial => 'travaux/form_cancel'  %></div>
			<% end %>
		<% end %>
	</div>
</div>

<div class="modal fade" id="cancelModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal" aria-label="close">&times;</button>
        <h4 class="modal-title">Annulation du travail</h4>
      </div>
      <div class="modal-body">
        <div class="field input-group">
          <span class="input-group-addon"><i class="fa fa-pencil fa-fw"></i></span>
          <%= text_area_tag "raisonCancelModal", nil, class: "form-control", placeholder: "Raisons de l'annulation", rows: "20", id: "raisonCancelModal" %>
        </div>
      </div>
      <div class="modal-footer">
        <button id="cancelModalButton" class="btn btn-primary">Annuler le travail</button>
      </div>
    </div>
  </div>
</div>

app/views/travaux/_form.html.erb
<%= form_for @travail, :html => { :class => "form-horizontal travail" } do |f| %>

    <% if @travail.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@travail.errors.count, "error") %> prohibited this travail from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @travail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-home fa-fw"></i></span>
      <%= f.select(:bien_id, [], {}, {class: "form-control"}) do %>
        <% @biens.each do |bien| %>
          <%= content_tag(:option, bien.nom_ref, value: bien.id, selected: (bien.id==@travail[:bien_id])) %>
        <% end %>
      <% end %>
      <%= error_span(@travail[:bien_id]) %>
    </div>
  </div>

  <div class="control-group">
    <div class="field input-group">
      <span class="input-group-addon"><i class="fa fa-wrench fa-fw"></i></span>
      <%= f.select(:travaux_type_id, [], {}, {class: "form-control"}) do %>
        <% TravauxType.all.each do |type| %>
          <%= content_tag(:option, type.nom, value: type.id, selected: (type.id==@travail[:travaux_type_id])) %>
        <% end %>
      <% end %>
      <%= error_span(@travail[:travaux_type_id]) %>
    </div>
  </div>

	<%= f.submit "Valider", :class => 'btn btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	          :back, :class => 'btn btn-default' %>


<% end %>

app/views/travaux/_messages.erb
<div class="col-md-12">
	<% @lignes.each do |ligne| %>
		<dt class="grey"><strong><%= I18n.l ligne.created_at.in_time_zone(current_user.timezone), format: :long_datetime %>:</strong></dt>
		<dd class="container_ligne">
			<% classe = ligne.message_automatique ? "ligne_travaux well" : "ligne_travaux well message" %>
      <% if ligne.piece_jointe? %>
        <div class="paperclip_block">
  				<%= link_to image_tag("paperclip.png", title: "Ouvrir la pièce jointe", class:"paperclip"), ligne.piece_jointe.url, target: "_blank" %>
  			</div>
      <% end %>
      <div class="<%=classe%>">
				<%= simple_format(ligne.detail) %>
			</div>
			<div class="useravatar">
				<%= image_tag ligne.user.avatar.url(:thumb), class: "img-responsive image_ronde", title: "par #{ligne.user.name}" %>
			</div>
		</dd>
	<% end %>
	<% unless @travail.cancel %>
	  <div class="bloc_bleu">
	  	<%= render :partial => 'travaux_lignes/form' %>
	  </div>
	<% end %>
</div>

app/views/travaux/_progress_bar.erb
<div class="row bs-wizard" style="border-bottom:0;">
  <% i = 1 %>
  <% TravauxStatut.order(:ordre).each do |statut| %>
  	<div class="col-xs-<%= (i==1 or i==10) ? 2 : 1 %> bs-wizard-step <%= (@travail.travaux_statut.ordre==statut.ordre ? 'active' : (@travail.travaux_statut.ordre>statut.ordre ? 'complete' : 'disabled')) %>">
      <div class="progress"><div class="progress-bar"></div></div>
      <a class="bs-wizard-dot"></a>
      <div class="bs-wizard-info text-center"><%= statut.nom %></div>
    </div>
    <% i += 1 %>
	<% end %>
</div>

app/views/travaux/edit.html.erb
<%- model_class = Travail -%>
<div class="titre_actif">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/travaux/index.html.erb
<script>
	app.controller('TravauxList', function($scope) {
	  $scope.travaux = gon.travaux;
	  $scope.predicate = 'ref';
	  $scope.reverse = true;
	  $scope.order = function(predicate) {
	    $scope.reverse = ($scope.predicate === predicate) ? !$scope.reverse : false;
	    $scope.predicate = predicate;
	  };
	  $scope.filter_show = true;
	  $scope.go = function(id) {
			window.document.location = '/travaux/'+id;
		};
	});
</script>

<%- model_class = Travail -%>
<div class="titre_actif">
  <h1><%= @titre %></h1>
</div>
<div ng-controller="TravauxList">
	<div class="table-responsive">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>
						<a href="" ng-click="order('type')">Type</a>
						<span class="sortorder" ng-show="predicate === 'type'" ng-class="{reverse:reverse}"></span>
					</th>
					<th>
						<a href="" ng-click="order('statut')">Statut</a>
						<span class="sortorder" ng-show="predicate === 'statut'" ng-class="{reverse:reverse}"></span>
					</th>
					<th>
						<a href="" ng-click="order('date')">Date</a>
						<span class="sortorder" ng-show="predicate === 'date'" ng-class="{reverse:reverse}"></span>
					</th>
					<th>
						<a href="" ng-click="order('bien')">Bien</a>
						<span class="sortorder" ng-show="predicate === 'bien'" ng-class="{reverse:reverse}"></span>
					</th>
					<th>
						<a href="" ng-click="order('proprietaire')">Propriétaire</a>
						<span class="sortorder" ng-show="predicate === 'proprietaire'" ng-class="{reverse:reverse}"></span>
					</th>
					<th>
						<a href="" ng-click="order('locataire')">Locataire</a>
						<span class="sortorder" ng-show="predicate === 'locataire'" ng-class="{reverse:reverse}"></span>
					</th>
					<th>
						<a href="" ng-click="order('prestataires')">Artisans</a>
						<span class="sortorder" ng-show="predicate === 'prestataires'" ng-class="{reverse:reverse}"></span>
					</th>
				</tr>
				<tr ng-show="filter_show">
					<td><input class="recherche form-control" ng-model="search.type" autofocus></td>
					<td><input class="recherche form-control" ng-model="search.statut"></td>
					<td><input class="recherche form-control" ng-model="search.date"></td>
					<td><input class="recherche form-control" ng-model="search.bien"></td>
					<td><input class="recherche form-control" ng-model="search.proprietaire"></td>
					<td><input class="recherche form-control" ng-model="search.locataire"></td>
					<td><input class="recherche form-control" ng-model="search.prestataires" id="search_prestataires"></td>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="travail in travaux | filter:search | orderBy:predicate:reverse" ng-click="go(travail.id)">
		    	<td>{{travail.type}}</td>
		      <td>{{travail.statut}}</td>
		      <td>{{travail.date}}</td>
		      <td>{{travail.bien}}</td>
		      <td>{{travail.proprietaire}}</td>
		      <td>{{travail.locataire}}</td>
		      <td>{{travail.prestataires}}</td>
	    	</tr>
			</tbody>
		</table>
	</div>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            @new_path,
            :class => 'btn btn-primary' %>

app/views/travaux/new.html.erb
<%- model_class = Travail -%>
<div class="titre_actif">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/travaux/show.html.erb
<% if @travail.cancel %>
  <div class="ribbon_cancel"><span>ANNULÉ</span></div>
<% elsif @travail.travaux_statut.ordre>=6.0 %>
  <div class="ribbon_done"><span>TERMINÉ</span></div>
<% end %>

<%- model_class = Travail -%>
<div class="titre_actif">
  <h1><%= "#{@travail.travaux_type.nom} - #{@travail.bien.nom}" %></h1>
</div>

<%= render :partial => 'progress_bar'  %>
<%= render :partial => 'en_tete'  %>
<%= render :partial => 'bloc_artisans'  %>
<%= render :partial => 'messages'  %>