config/routes.rb
Rails.application.routes.draw do
  resources :importations
  resources :superviseurs
  resources :tiers_types
  resources :users
  resource :user_sessions, only: [:create, :new, :destroy]
  resources :travaux_artisans
  get 'config' => 'config#index'
  resources :travaux
  resources :biens
  resources :tiers
  root 'home#index'
  get 'home/index'

  get 'statistiques' => 'statistiques#index'

	resources :travaux_statuts
	resources :travaux_types
  resources :travaux_lignes
	resources :bien_types

  resources :societes, only: [:edit, :update]

	post 'newligne' => 'travaux#newligne'

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'factures' => 'factures#index'
  post 'factures' => 'factures#paye'
  post 'factures_envoye' => 'factures#envoye'

end

app/models/bien.rb
class Bien < ActiveRecord::Base

	validates :ville,  :presence => true

	belongs_to :proprietaire, :class_name => 'Tier', :foreign_key => 'proprietaire_id'
	belongs_to :locataire, :class_name => 'Tier', :foreign_key => 'locataire_id'
	belongs_to :coproprietaire, :class_name => 'Tier', :foreign_key => 'coproprietaire_id'
	belongs_to :colocataire, :class_name => 'Tier', :foreign_key => 'colocataire_id'
	belongs_to :syndic, :class_name => 'Tier', :foreign_key => 'syndic_id'

	belongs_to :bien_type
	has_many :travaux

	def nom
		return "#{self.bien_type.nom} sur #{self.ville}"
	end

	def nom_ref
		return "#{self.nom} (#{self.ref})"
	end

	def adresse_complete
		return "#{self.adresse}\n#{self.cp} #{self.ville}"
	end
end

app/models/bien_type.rb
class BienType < ActiveRecord::Base
	has_many :biens
end

app/models/importation.rb
class Importation < ActiveRecord::Base
  validates :titre,  :presence => true
  validates :user_id,  :presence => true
  validates :fichier,  :presence => true

  has_attached_file :fichier
  do_not_validate_attachment_file_type :fichier
  belongs_to :user
  self.inheritance_column = :_type_disabled
end

app/models/messagerie.rb
class Messagerie < ActiveRecord::Base
	belongs_to :user
	belongs_to :travaux_ligne
end

app/models/societe.rb
class Societe < ActiveRecord::Base
	has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/models/superviseur.rb
class Superviseur < ActiveRecord::Base
	belongs_to :user
	belongs_to :travail
end

app/models/tier.rb
class Tier < ActiveRecord::Base
	validates :tiers_type_id,  :presence => true
	belongs_to :tiers_type
	has_many :biens
	has_many :travaux

	def nom_complet
		return "#{self.raison_sociale} #{self.nom} #{self.prenom}"
	end

	def statut
		stat = []
		stat << "Propriétaire" if self.is_proprietaire
		stat << "Locataire" if self.is_locataire
		stat << "Prestataire" if self.is_prestataire
		return stat
	end
end

app/models/tiers_type.rb
class TiersType < ActiveRecord::Base
	has_many :tiers
end

app/models/travail.rb
class Travail < ActiveRecord::Base
	validates :bien_id,  :presence => true
	validates :travaux_type_id,  :presence => true
	validates :travaux_statut_id,  :presence => true
	validates :user_id,  :presence => true
	belongs_to :travaux_statut
	belongs_to :bien
	belongs_to :travaux_type
	belongs_to :tier, foreign_key: "prestataire_id"
	belongs_to :user
	has_many :travaux_lignes, :dependent => :delete_all
	has_many :travaux_artisans, :dependent => :delete_all
	has_many :superviseurs, :dependent => :delete_all
end

app/models/travaux_artisan.rb
class TravauxArtisan < ActiveRecord::Base
	belongs_to :travail
	belongs_to :tier
	has_attached_file :devis
	do_not_validate_attachment_file_type :devis
	has_attached_file :accord
	do_not_validate_attachment_file_type :accord
	has_attached_file :facture
	do_not_validate_attachment_file_type :facture
	has_attached_file :fin_travaux
	do_not_validate_attachment_file_type :fin_travaux
	has_attached_file :accord_bailleur_fichier
	do_not_validate_attachment_file_type :accord_bailleur_fichier
end

app/models/travaux_ligne.rb
class TravauxLigne < ActiveRecord::Base
	validates :detail,  :presence => true
	validates :user_id,  :presence => true
	validates :travail_id,  :presence => true
	belongs_to :travail
	belongs_to :user
	has_many :messagerie, :dependent => :delete_all
	has_attached_file :piece_jointe
	#validates_attachment :piece_jointe, content_type: { content_type: "application/pdf" }
	do_not_validate_attachment_file_type :piece_jointe

	after_create :envoi_sur_messagerie

	private
		def envoi_sur_messagerie
			superviseurs = Superviseur.where(travail_id: self.travail_id)
			superviseurs.each do |superviseur|
				Messagerie.create(travaux_ligne_id: self.id, user_id: superviseur.user_id) unless self.user_id==superviseur.user_id
			end
		end
end

app/models/travaux_statut.rb
class TravauxStatut < ActiveRecord::Base
	has_many :travaux
end

app/models/travaux_type.rb
class TravauxType < ActiveRecord::Base
	has_many :travaux
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic do |c|
		c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_many :travaux_lignes
  has_many :travaux

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end  

app/controllers/travaux_lignes_controller.rb
class TravauxLignesController < ApplicationController
  before_action :set_travaux_ligne, only: [:show, :edit, :update, :destroy]

  # GET /travaux_lignes
  # GET /travaux_lignes.json
  def index
    @travaux_lignes = TravauxLigne.all
  end

  # GET /travaux_lignes/1
  # GET /travaux_lignes/1.json
  def show
  end

  # GET /travaux_lignes/new
  def new
    @travaux_ligne = TravauxLigne.new
  end

  # GET /travaux_lignes/1/edit
  def edit
  end

  # POST /travaux_lignes
  # POST /travaux_lignes.json
  def create
    @travaux_ligne = TravauxLigne.new(travaux_ligne_params)
    @travaux_ligne.user_id = current_user.id
    respond_to do |format|
      if @travaux_ligne.save
        format.html { redirect_to travail_path(@travaux_ligne.travail_id), notice: 'Travaux ligne was successfully created.' }
        format.json { render :show, status: :created, location: @travaux_ligne }
      else
        format.html { render :new }
        format.json { render json: @travaux_ligne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travaux_lignes/1
  # PATCH/PUT /travaux_lignes/1.json
  def update
    respond_to do |format|
      if @travaux_ligne.update(travaux_ligne_params)
        format.html { redirect_to @travaux_ligne, notice: 'Travaux ligne was successfully updated.' }
        format.json { render :show, status: :ok, location: @travaux_ligne }
      else
        format.html { render :edit }
        format.json { render json: @travaux_ligne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travaux_lignes/1
  # DELETE /travaux_lignes/1.json
  def destroy
    @travaux_ligne.destroy
    respond_to do |format|
      format.html { redirect_to travaux_lignes_url, notice: 'Travaux ligne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travaux_ligne
      @travaux_ligne = TravauxLigne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travaux_ligne_params
      params.require(:travaux_ligne).permit(:detail, :travail_id, :piece_jointe)
    end
end

app/helpers/biens_helper.rb
module BiensHelper
end

app/helpers/config_helper.rb
module ConfigHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/helpers/travaux_helper.rb
module TravauxHelper
end

app/helpers/travaux_lignes_helper.rb
module TravauxLignesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/travaux_lignes/_form.html.erb
<%= form_for @travaux_ligne, :html => { :class => "form-horizontal travaux_type" } do |f| %>

    <% if @travaux_ligne.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@travaux_ligne.errors.count, "error") %> prohibited this travaux_ligne from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @travaux_ligne.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <dt class="grey"><strong><%= I18n.l DateTime.now, format: :short_datetime %>:</strong></dt>
    <div class="controls">
      <%= f.text_area :detail, :class => 'form-control' %>
    </div>
    <%= error_span(@travaux_ligne[:detail]) %>
  </div>

  <%= f.text_field :travail_id, :hidden => true %>

  <div class="control-group">
    <dt class="grey"><strong><%= f.label :piece_jointe, :class => 'control-label' %>:</strong></dt>
    <div class="controls">
      <%= f.file_field :piece_jointe, :class => 'form-control' %>
    </div>
    <%= error_span(@travaux_ligne[:piece_jointe]) %>
  </div>
  <br/>
  <%= f.submit "Valider", :class => 'btn btn-primary' %>

<% end %>

app/views/travaux_lignes/edit.html.erb
<%- model_class = TravauxLigne -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/travaux_lignes/index.html.erb
<%- model_class = TravauxLigne -%>
<div class="titre_actif">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:detail) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @travaux_lignes.each do |travaux_ligne| %>
      <tr>
        <td><%= link_to travaux_ligne.id, travaux_ligne_path(travaux_ligne) %></td>
        <td><%= travaux_ligne.detail %></td>
        <td><%=l travaux_ligne.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_travaux_ligne_path(travaux_ligne), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      travaux_ligne_path(travaux_ligne),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_travaux_ligne_path,
            :class => 'btn btn-primary' %>

app/views/travaux_lignes/new.html.erb
<%- model_class = TravauxLigne -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/travaux_lignes/show.html.erb
<%- model_class = TravauxLigne -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:detail) %>:</strong></dt>
  <dd><%= @travaux_ligne.detail %></dd>
  <dt><strong><%= model_class.human_attribute_name(:travail_id) %>:</strong></dt>
  <dd><%= @travaux_ligne.travail_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:piece_jointe) %>:</strong></dt>
  <dd><%= link_to @travaux_ligne.piece_jointe, @travaux_ligne.piece_jointe.url, :target => "_blank" %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              travaux_lignes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_travaux_ligne_path(@travaux_ligne), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              travaux_ligne_path(@travaux_ligne),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>