config/routes.rb
Rails.application.routes.draw do
  resources :importations
  resources :superviseurs
  resources :tiers_types
  resources :users
  resource :user_sessions, only: [:create, :new, :destroy]
  resources :travaux_artisans
  get 'config' => 'config#index'
  resources :travaux
  resources :biens
  resources :tiers
  root 'home#index'
  get 'home/index'

  get 'statistiques' => 'statistiques#index'

	resources :travaux_statuts
	resources :travaux_types
  resources :travaux_lignes
	resources :bien_types

  resources :societes, only: [:edit, :update]

	post 'newligne' => 'travaux#newligne'

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'factures' => 'factures#index'
  post 'factures' => 'factures#paye'
  post 'factures_envoye' => 'factures#envoye'

end

app/models/travaux_artisan.rb
class TravauxArtisan < ActiveRecord::Base
	belongs_to :travail
	belongs_to :tier
	has_attached_file :devis
	do_not_validate_attachment_file_type :devis
	has_attached_file :accord
	do_not_validate_attachment_file_type :accord
	has_attached_file :facture
	do_not_validate_attachment_file_type :facture
	has_attached_file :fin_travaux
	do_not_validate_attachment_file_type :fin_travaux
	has_attached_file :accord_bailleur_fichier
	do_not_validate_attachment_file_type :accord_bailleur_fichier
end

app/controllers/travaux_artisans_controller.rb
class TravauxArtisansController < ApplicationController
  include ApplicationHelper
  before_action :set_travaux_artisan, only: [:show, :edit, :update, :destroy]

  # GET /travaux_artisans
  # GET /travaux_artisans.json
  def index
    @travaux_artisans = TravauxArtisan.all
  end

  # GET /travaux_artisans/1
  # GET /travaux_artisans/1.json
  def show
  end

  # GET /travaux_artisans/new
  def new
    @travaux_artisan = TravauxArtisan.new
  end

  # GET /travaux_artisans/1/edit
  def edit
  end

  # POST /travaux_artisans
  # POST /travaux_artisans.json
  def create
    @travaux_artisan = TravauxArtisan.new(travaux_artisan_params)

    respond_to do |format|
      if @travaux_artisan.save
        ligne = TravauxLigne.create(travail_id: @travaux_artisan.travail_id,
            												detail: "Ajout de #{@travaux_artisan.tier.nom_complet} a la liste des artisans pour ce travail",
                                    message_automatique: true,
            												user_id: current_user.id)
        format.html { redirect_to travail_path(@travaux_artisan.travail_id), notice: 'Travaux artisan was successfully created.' }
        format.json { render :show, status: :created, location: @travaux_artisan }
      else
        format.html { render :new }
        format.json { render json: @travaux_artisan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travaux_artisans/1
  # PATCH/PUT /travaux_artisans/1.json
  def update
    respond_to do |format|
      demande = @travaux_artisan.demande ? 1 : 0
      bailleur = @travaux_artisan.bailleur ? 1 : 0
      fin_travaux = @travaux_artisan.fin_travaux ? 1 : 0
      paye = @travaux_artisan.paye ? 1 : 0
      bon_pour_paiement = @travaux_artisan.bon_pour_paiement ? 1 : 0
      accord_check = @travaux_artisan.accord_check ? 1 : 0
      result = false
      cc = params["cc"]

    	message = nil
      pj = nil
      type_mail = nil
      if demande!=travaux_artisan_params["demande"].to_i
        @travaux_artisan.travail.update(travaux_statut_id: 12) if @travaux_artisan.travail.travaux_statut.ordre < 1.5
    		message = ""
        mail = params["mail"]
        if mail.to_s.empty?
          message = "Demande travaux envoyée manuellement à #{@travaux_artisan.tier.nom_complet}"
        else
          message = "Demande travaux envoyée par courriel à #{@travaux_artisan.tier.nom_complet} - #{@travaux_artisan.tier.email}\n\n#{cc ? 'cc: '+cc : ''}\n\n#{mail}"
        end
        pdf = TravauxArtisansHelper::FicheIntervention.new(@travaux_artisan.id, travaux_artisan_params["fi_devis"]=="1", travaux_artisan_params["fi_details"], travaux_artisan_params["fi_montant"])
        file = StringIO.new(pdf.render)
        file.class.class_eval { attr_accessor :original_filename, :content_type } #add attr's that paperclip needs
        file.original_filename = "fiche_intervention_travaux_#{@travaux_artisan.id}.pdf"
        file.content_type = "application/pdf"
        pj = file
        type_mail = "demande_intervention" unless mail.to_s.empty?
    	end
      if travaux_artisan_params["devis"]
    		@travaux_artisan.travail.update(travaux_statut_id: 2) if @travaux_artisan.travail.travaux_statut.ordre < 2.0
				message = "Réception du devis de #{@travaux_artisan.tier.nom_complet}"
        pj = travaux_artisan_params["devis"]
    	end
      if bailleur!=travaux_artisan_params["bailleur"].to_i
        @travaux_artisan.travail.update(travaux_statut_id: 13) if @travaux_artisan.travail.travaux_statut.ordre < 2.2
        pj = @travaux_artisan.devis
        mail = params["mail"]
        message = "Devis de #{@travaux_artisan.tier.nom_complet} envoyé#{mail.to_s.empty? ? " manuellement" : ""} au bailleur"
        message += "\n\n#{mail}" unless mail.to_s.empty?
        type_mail = "devis_bailleur" unless mail.to_s.empty?
    	end
      if params["retour_bailleur"]
        @travaux_artisan.travail.update(travaux_statut_id: 14) if @travaux_artisan.travail.travaux_statut.ordre < 2.5
        if travaux_artisan_params["accord_bailleur"]=="1"
          message = "Réception du bon pour accord du bailleur pour le devis de #{@travaux_artisan.tier.nom_complet}\n\n#{travaux_artisan_params["accord_bailleur_message"]}"
        else
          message = "Le bailleur refuse le devis de #{@travaux_artisan.tier.nom_complet}\n\n#{travaux_artisan_params["accord_bailleur_message"]}"
        end
        pj = travaux_artisan_params["accord_bailleur_fichier"]
      end
    	if accord_check!=travaux_artisan_params["accord_check"].to_i
    		@travaux_artisan.travail.update(travaux_statut_id: 3) if @travaux_artisan.travail.travaux_statut.ordre < 3.0
				message = "Envoi#{mail.to_s.empty? ? " manuel" : ""} du bon pour accord du devis à l'artisan #{@travaux_artisan.tier.nom_complet}"
        `pdftk "#{Rails.root.join('public', @travaux_artisan.devis.path)}" multistamp #{Rails.root.join('tmp', 'pdf', 'bpa.pdf')} output "#{Rails.root.join('tmp', 'pdf', @travaux_artisan.devis_file_name)}"`
        pj = File.open(Rails.root.join('tmp', 'pdf', @travaux_artisan.devis_file_name))
        mail = params["mail"]
        message += "\n\n#{mail}" unless mail.to_s.empty?
        type_mail = "bpa" unless mail.to_s.empty?
    	end
    	if travaux_artisan_params["facture"]
    		@travaux_artisan.travail.update(travaux_statut_id: 5) if @travaux_artisan.travail.travaux_statut.ordre < 5.0
				message = "Réception de la facture de #{@travaux_artisan.tier.nom_complet}"
        pj = travaux_artisan_params["facture"]
    	end
    	if travaux_artisan_params["fin_travaux"]
    		@travaux_artisan.travail.update(travaux_statut_id: 4) if @travaux_artisan.travail.travaux_statut.ordre < 4.0
    		message = "#{@travaux_artisan.tier.nom_complet} a fini les travaux"
        pj = travaux_artisan_params["fin_travaux"]
    	end
    	if paye!=travaux_artisan_params["paye"].to_i
    		@travaux_artisan.travail.update(travaux_statut_id: 6) if @travaux_artisan.travail.travaux_statut.ordre < 6.0
    		message = "Rôle Gercop: paiement de la facture de #{@travaux_artisan.tier.nom_complet}"
    	end
      if bon_pour_paiement!=travaux_artisan_params["bon_pour_paiement"].to_i
        @travaux_artisan.travail.update(travaux_statut_id: 15) if @travaux_artisan.travail.travaux_statut.ordre < 5.5
    		message = "Bon pour paiement de la facture de #{@travaux_artisan.tier.nom_complet}\nType de bpp : #{@travaux_artisan.type_paiement}"
    	end
    	if message
	    	ligne = TravauxLigne.create(travail_id: @travaux_artisan.travail_id,
																		detail: message,
																		message_automatique: true,
                                    piece_jointe: pj,
																		user_id: current_user.id)
        if ligne
          result = @travaux_artisan.update(travaux_artisan_params)
          if accord_check!=travaux_artisan_params["accord_check"].to_i
            @travaux_artisan.accord = pj
            @travaux_artisan.save
          end
          if type_mail
            to = nil
            sujet = nil
            case type_mail
            when "demande_intervention"
              to = @travaux_artisan.tier.email
              sujet = "Demande d'intervention"
            when "devis_bailleur"
              to = @travaux_artisan.travail.bien.proprietaire.email
              sujet = "Devis pour travaux"
            when "bpa"
              to = @travaux_artisan.tier.email
              sujet = "Bon pour accord"
            end
            TravauxArtisanMailer.mail_travaux_artisan(current_user.email, to, mail, ligne, sujet, cc).deliver_now
          end
        end
	  	else
        result = @travaux_artisan.update(travaux_artisan_params)
      end
      if result
        format.html { redirect_to :back, notice: 'Travaux artisan was successfully updated.' }
        format.json { render :show, status: :ok, location: @travaux_artisan }
      else
        format.html { render :edit }
        format.json { render json: @travaux_artisan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travaux_artisans/1
  # DELETE /travaux_artisans/1.json
  def destroy
    ligne = TravauxLigne.create(travail_id: @travaux_artisan.travail_id,
        												detail: "#{@travaux_artisan.tier.nom_complet} a été retiré de la liste des artisans pour ce travail",
                                message_automatique: true,
        												user_id: current_user.id)
    @travaux_artisan.destroy
    respond_to do |format|
      format.html { redirect_to travail_path(@travaux_artisan.travail_id), notice: 'Travaux artisan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travaux_artisan
      @travaux_artisan = TravauxArtisan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travaux_artisan_params
      params.require(:travaux_artisan).permit(:travail_id, :tier_id, :devis, :bailleur, :accord, :accord_check, :facture, :demande, :paye, :fin_travaux, :bon_pour_paiement, :type_paiement, :fi_devis, :fi_details, :fi_montant, :accord_bailleur, :accord_bailleur_message, :accord_bailleur_fichier)
    end
end

app/helpers/travaux_artisans_helper.rb
module TravauxArtisansHelper
  class FicheIntervention < Prawn::Document

  	def initialize id, fi_devis=true, fi_details=nil, fi_montant=nil, fichier=nil

  		super(
  					:page_layout => :portrait,
  					:page_size => 'A4'
  			 	 )

      @societe = Societe.find(1)
      @travaux_artisan = TravauxArtisan.find(id)
      @superviseur = Superviseur.where(travail_id: @travaux_artisan.travail_id).first
      @fi_devis = fi_devis
      @fi_details = fi_details
      @fi_montant = fi_montant
  		en_tete
  		corps id
  		rendu fichier if fichier
  	end

  	def en_tete

  		image @societe.logo.path, :height => 100 if @societe.logo?
  		width = 140
  		bounding_box([bounds.right-width, bounds.top], :width => width) do
  		 text "<b><i>TRANSACTION\n\nVENTE - LOCATION\n\nGESTION</i></b>", size: 12, inline_format: true
   		end
   		padding = 5
   		rectangle [bounds.right-width-padding, bounds.top+padding*2], width+padding, 90
   		stroke

  		bounding_box([bounds.left, bounds.top-120], :width => bounds.right) do
  		 text "#{@societe.adresse} – #{@societe.cp} #{@societe.ville} – Tél. : #{@societe.tel}   Fax : #{@societe.fax}", size: 10, inline_format: true, align: :center
       if @superviseur
         text "<u>Rôle travaux:</u> #{@superviseur.user.name}   –   #{@superviseur.user.tel}   –   email: #{@superviseur.user.email}", size: 10, inline_format: true, align: :center
       end
   		end

   		self.line_width = 5
   		stroke_color 'ffd231'
   		y = bounds.top-124
   		stroke do
   			horizontal_line bounds.left, 50, :at => y
   			horizontal_line bounds.right-50, bounds.right, :at => y
   		end
  	end

  	def corps id
  		y = bounds.top-170
  		bounding_box([bounds.left, y], :width => bounds.right) do
  		 text "<b>FICHE D'INTERVENTION TRAVAUX - #{Date.today.strftime('%d/%m/%Y')}</b>", size: 18, inline_format: true, :align => :center
   		end
   		padding = 5
   		stroke_color '000000'
   		self.line_width = 1
   		padding = 5
   		rectangle [bounds.left, y+padding],  bounds.right, 22
   		stroke

   		y = bounds.top-210
  		bounding_box([bounds.left+padding, y], :width => bounds.right) do
  		 text "<u>ENTREPRISE :</u> #{@travaux_artisan.tier.nom_complet}", size: 12, inline_format: true
  		 text "#{@travaux_artisan.tier.portable}            #{@travaux_artisan.tier.tel}", size: 12
  		 text "#{@travaux_artisan.tier.email}", size: 12
   		end
   		rectangle [bounds.left, y+padding],  bounds.right, 50
   		stroke

      bien = @travaux_artisan.travail.bien
   		y = cursor-20
  		bounding_box([bounds.left+padding, y], :width => bounds.right) do
  		 text "<u>LOCATAIRE :</u> #{bien.locataire ? bien.locataire.nom_complet : ""}", size: 12, inline_format: true
  		 text "#{bien.locataire ? bien.locataire.portable : ""}            #{bien.locataire ? bien.locataire.tel : ""}", size: 12
  		 text "#{bien.locataire ? bien.locataire.email : ""}", size: 12
  		 text "\n<b><u>Adresse de l'intervention :</u></b>", size: 12, inline_format: true
       text "#{bien.adresse} #{bien.cp} #{bien.ville}", size: 12, inline_format: true
  		 text "\n<u>PROPRIETAIRE :</u> #{bien.proprietaire.nom_complet}", size: 12, inline_format: true
  		 text "<b><u>Facturation</u>                    <u>Chez ACCORD IMMOBILIER</u></b>", size: 12, inline_format: true
  		 text "\nJoindre à la facture la fiche d'intervention signée", size: 12, inline_format: true
   		end
   		rectangle [bounds.left, y+padding],  bounds.right, y-cursor+padding
   		stroke

   		y = cursor-20
  		bounding_box([bounds.left+padding, y], :width => bounds.right) do
  		 text "<b>DEMANDE D'INTERVENTION</b>", size: 18, inline_format: true, :align => :center
  		 text "\n<b><u>Devis avant travaux :</u>      #{@fi_devis ? "OUI #{@fi_montant.to_f>0.0 ? "SI MONTANT SUPERIEUR A #{@fi_montant} €" : ""}" : "NON"}</b>", size: 12, inline_format: true
  		 text "\n<b><u>Anomalies constatées / Travaux à réaliser : </u></b>\n#{@fi_details}", size: 12, inline_format: true
   		end
   		rectangle [bounds.left, y+padding],  bounds.right, y-cursor+padding
   		stroke

   		y = cursor-20
  		bounding_box([bounds.left+padding, y], :width => bounds.right) do
  		 text "<b>FICHE D'INTERVENTION</b>", size: 18, inline_format: true, :align => :center
  		 text "\n<b><u>Date d'intervention et délai d'exécution :</u></b>", size: 12, inline_format: true
  		 text "\n\n\n<b><u>Signature Locataire :\n\n\n\n</u></b>", size: 12, inline_format: true
   		end
   		rectangle [bounds.left, y+padding],  bounds.right, y-cursor+padding
   		stroke
  	end

  	def rendu fichier
  		render_file fichier
  	end

  end
end

app/views/travaux_artisans/_form.html.erb
<%= form_for(@travaux_artisan) do |f| %>
  <div class="field">
    <%= f.number_field :travail_id, hidden: true %>
  </div>
  <div class="field">
    <%= f.number_field :tier_id, hidden: true %>
  </div>

  <div class="field">
  	<%= f.file_field :devis, id: "devis#{@travaux_artisan.id}", style: "display:none", accept: 'application/pdf', onchange: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.check_box :bailleur, id: "bailleur#{@travaux_artisan.id}", style: "display:none", onclick: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.file_field :accord, id: "accord#{@travaux_artisan.id}", style: "display:none", accept: 'application/pdf', onchange: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.check_box :accord_check, id: "accord_check#{@travaux_artisan.id}", style: "display:none", onclick: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.file_field :facture, id: "facture#{@travaux_artisan.id}", style: "display:none", accept: 'application/pdf', onchange: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.check_box :demande, id: "demande#{@travaux_artisan.id}", style: "display:none", onclick: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.file_field :fin_travaux, id: "fin_travaux#{@travaux_artisan.id}", style: "display:none", accept:  'application/pdf', onchange: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.check_box :bon_pour_paiement, id: "bon_pour_paiement#{@travaux_artisan.id}", style: "display:none", onclick: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.check_box :paye, id: "paye#{@travaux_artisan.id}", style: "display:none", onclick: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
  </div>
  <div class="field">
  	<%= f.check_box :fi_devis, id: "fi_devis#{@travaux_artisan.id}" %>
  </div>
  <div class="field">
  	<%= f.text_area :fi_details, id: "fi_details#{@travaux_artisan.id}" %>
  </div>
  <div class="field">
  	<%= f.text_field :fi_montant, id: "fi_montant#{@travaux_artisan.id}" %>
  </div>
  <div class="field">
  	<%= f.check_box :accord_bailleur, id: "accord_bailleur#{@travaux_artisan.id}" %>
  </div>
  <div class="field">
  	<%= f.text_area :accord_bailleur_message, id: "accord_bailleur_message#{@travaux_artisan.id}" %>
  </div>
  <div class="field">
  	<%= f.file_field :accord_bailleur_fichier, id: "accord_bailleur_fichier#{@travaux_artisan.id}" %>
  </div>
  <div class="field">
  	<%= check_box_tag "retour_bailleur", nil, false, id: "retour_bailleur#{@travaux_artisan.id}", onclick: "$('#submit#{@travaux_artisan.id}').trigger('click');" %>
    <p>Valide retour</p>
  </div>
  <div class="field">
  	<%= text_field_tag "cc", nil, id: "cc#{@travaux_artisan.id}" %>
  </div>
  <div class="actions">
    <%= f.submit id: "submit#{@travaux_artisan.id}", hidden: true %>
  </div>
  <div class="field">
    <%= f.text_field :type_paiement, id: "type_paiement#{@travaux_artisan.id}" %>
  </div>

  <textarea name="mail" id=<%="mail#{@travaux_artisan.id}"%> style="display:none;" ></textarea>

<% end %>

app/views/travaux_artisans/edit.html.erb
<h1>Editing Travaux Artisan</h1>

<%= render 'form' %>

<%= link_to 'Show', @travaux_artisan %> |
<%= link_to 'Back', travaux_artisans_path %>

app/views/travaux_artisans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Travaux Artisans</h1>

<table>
  <thead>
    <tr>
      <th>Travail</th>
      <th>Tier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @travaux_artisans.each do |travaux_artisan| %>
      <tr>
        <td><%= travaux_artisan.travail_id %></td>
        <td><%= travaux_artisan.tier_id %></td>
        <td><%= link_to 'Show', travaux_artisan %></td>
        <td><%= link_to 'Edit', edit_travaux_artisan_path(travaux_artisan) %></td>
        <td><%= link_to 'Destroy', travaux_artisan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Travaux artisan', new_travaux_artisan_path %>

app/views/travaux_artisans/new.html.erb
<h1>New Travaux Artisan</h1>

<%= render 'form' %>

<%= link_to 'Back', travaux_artisans_path %>

app/views/travaux_artisans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Travail:</strong>
  <%= @travaux_artisan.travail_id %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @travaux_artisan.tier_id %>
</p>

<%= link_to 'Edit', edit_travaux_artisan_path(@travaux_artisan) %> |
<%= link_to 'Back', travaux_artisans_path %>